val CLUB_SEVEN: PlayingCard = PlayingCard(Suit.CLUB, Denomination.SEVEN)
val CLUB_THREE: PlayingCard = PlayingCard(Suit.CLUB, Denomination.THREE)
val CLUB_TWO: PlayingCard = PlayingCard(Suit.CLUB, Denomination.TWO)
val CLUB_ACE: PlayingCard = PlayingCard(Suit.CLUB, Denomination.ACE)
val CLUB_KING: PlayingCard = PlayingCard(Suit.CLUB, Denomination.KING)
